#!/system/bin/sh
#
# Script for TV power control from a box
# Intercept "Power" button, detect a TV state and toggle it
# Version 2.0
#

# button code from getevent to watch
# To get a button code please perform the following actions:
#   (You might have a root privilege)
#
# 1. Open Android terminal (also ADB shell is well enough)
# 2. Run: getevent
# 3. Click several times on desired button
# 4. Press Ctrl-C to break getevent
# 5. Take a code from the third line at the end of the getevent output
BUTTON="0004 00010081"

# 6. Note an input device from getevent output and set it here
# Input device
INPUT=/dev/input/event4

# A value of CEC_RX_CNT parameter in /sys/class/cec/dump_reg file when a TV is in standby mode
# Sony Samsung
IS_OFF="0x09 0x02"
# Codes in mode on
IS_ON="0x05 0x04"

# Set log file for messaging
LOG=/sdcard/tv_onoff.log

sleep 5

echo "Start TV on_off" > $LOG

# Wait until boot is complete
while [ ""`getprop dev.bootcomplete` != "1" ] ; do echo "Waitiing until boot is complete" >> $LOG; sleep 3; done


function initState() {
	echo "Init state of TV" >> $LOG

	return

	echo 0xF0 0x8F > /sys/class/cec/cmd
	sleep 2
	isOn
	local res=$?

	if [ "$res" = "2" ]; then
		echo "Cannot detect a tv state" >> $LOG
	fi
	if [ "$res" = "1" ]; then
		echo "TV is on" >> $LOG
	fi
	if [ "$res" = "0" ]; then
		echo "TV is off" >> $LOG
	fi
}
function turnOff() {
	echo "Turning off" >> $LOG
	# Samsung/Sony
	echo 0xF0 0x36 > /sys/class/cec/cmd
}
function turnOn() {
	echo "Waking up" >> $LOG
	# Samsung/Sony
	echo 0xF0 0x04 > /sys/class/cec/cmd
}
function tryOnOff() {

	echo "Try to turn off" >> $LOG
	turnOff
	sleep 0.6

	isOn
	local res=$?

	if [ "$res" = "2" ]; then
		echo "Try to turn on" >> $LOG
		turnOn
	fi
}

function isOn() {
	line=`cat /sys/class/cec/dump_reg|grep CEC_RX_CNT | sed -n "s/^.*=.*\(0x[0-9]\{2\}\)\s*$/\1/p"`

	if [ "$line" = "0x00" ]; then
		return 2
	fi

	for code in $IS_ON
	do
		if [ "$line" = "$code" ]; then
			return 1
		fi
	done

	for code in $IS_OFF
	do
		if [ "$line" = "$code" ]; then
			return 0
		fi
	done

	return 1
}

function isOn2() {
  # Query power status
  echo 0xF0 0x8F > /sys/class/cec/cmd

  counter=1
  while [ $counter -le 6 ]
  do
    sleep 0.15

    code=`cat /sys/class/cec/dump_reg|grep "RX buffer:" | sed -n "s/^.*: 0f 90 \([0-9]\{2\}\) .*$/\1/p"`

    if [ "$code" = "01" ]; then
      return 0
    fi

    if [ "$code" = "00" ]; then
      return 1
    fi

    ((counter++))
  done

	return 2
}


###
### A main code
###

initState

while do
#	input=`getevent -c 4 -n $INPUT`
	input=`getevent -c 4 -n`
	code=`echo $input | sed -n "s/^.*\($BUTTON\).*$/\1/p"`

	if [ "$code" = "$BUTTON" ] ; then

		isOn2
		local res=$?
		if [ "$res" = "2" ]; then
			tryOnOff
		else
			if [ "$res" = "1" ] ; then
				turnOff
			else
				turnOn
			fi
		fi
	else
		echo $input >> $LOG
	fi
done

###
### Version History
### 2.0 Read TV state
### 1.1 Add Samsung support
### 1.0 First draft. Only Sony support
###
