#!/system/bin/sh
#
# Script for TV power control from a box
# Intercept "Power" button, detect a TV state and toggle it
# Version 1.1
#

# button code from getevent to watch
# To get a button code please perform the following actions:
#   (You might have a root privilege)
#
# 1. Open Android terminal (also ADB shell is well enough)
# 2. Run: getevent
# 3. Click several times on desired button
# 4. Press Ctrl-C to break getevent
# 5. Take a code from the third line at the end of the getevent output
BUTTON="0004 00010081"

# 6. Note an input device from getevent output and set it here
# Input device
INPUT=/dev/input/event4

# A value of CEC_RX_CNT parameter in /sys/class/cec/dump_reg file when a TV is in standby mode
IS_OFF1="0x09"
IS_OFF2="0x02"

# Wait until boot is complete
while [ ""`getprop dev.bootcomplete` != "1" ] ; do sleep 1; done

# Set log file for messaging
LOG=/sdcard/tv_onoff.log



function turnOff() {
	echo "Turning off" >> $LOG
	# Sony
	# echo 0x40 0x36 > /sys/class/cec/cmd
	# Samsung/Sony
	echo 0xF0 0x36 > /sys/class/cec/cmd
}
function turnOn() {
	echo "Waking up" >> $LOG
	# Sony
	# echo 0x40 0x04 > /sys/class/cec/cmd
	# Samsung/Sony
	echo 0xF0 0x04 > /sys/class/cec/cmd
}

function isOn() {
	line=`cat /sys/class/cec/dump_reg|grep CEC_RX_CNT | sed -n "s/^.*=.*\(0x[0-9]\{2\}\)\s*$/\1/p"`
	if [ "$line" = "$IS_OFF1" ] || [ "$line" = "$IS_OFF2" ]; then
		return 0
	else
		return 1
	fi
}


###
### A main code
###
echo tv_on_off init done > $LOG

while do
	input=`getevent -c 6 -n $INPUT`
	code=`echo $input | sed -n "s/^.*\($BUTTON\).*$/\1/p"`

	if [ "$code" = "$BUTTON" ] ; then

		isOn
		local res=$?
		if [ "$res" = "1" ] ; then
			turnOff
		else
			turnOn
		fi
	else
		echo $input >> $LOG
	fi
done

###
### Version History
### 1.1 Add Samsung support
### 1.0 First draft. Only Sony support
###